[[sites]]
name = "Dhaval Soneji"
url = "https://dhavalsoneji.com/"

[[sites]]
name = "William Grant"
url = "https://wdhg.me"

[[sites]]
name = "Stefan Radziuk"
url = "https://stefan.radzi.uk/"

[[sites]]
name = "Noor Sawhney"
url = "https://noor.fyi/"
